language: python
python: 2.7
env:
  - TOX_ENV=py27-sphinx13
  - TOX_ENV=py27-sphinx14
  - TOX_ENV=py34-sphinx13
  - TOX_ENV=py34-sphinx14
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
matrix:
  include:
    - python: 3.5
      env:
        - TOX_ENV=py35-sphinx13
        - TOX_ENV=py35-sphinx14
